# Updated wrangler.toml for your existing books-api-proxy worker
# Copy this content to your actual wrangler.toml file

name = "books-api-proxy"
main = "proxy-bulletproof-logging.js"
compatibility_date = "2024-08-24"
compatibility_flags = ["nodejs_compat"]

# CRITICAL: Add this tail worker binding
tail_consumers = [
  { service = "books-proxy-tail-worker" }
]

# Your existing environment variables (keep your current ones)
[vars]
# Add any environment variables you currently have

# Your existing KV namespace binding (update with your actual ID)
[[kv_namespaces]]
binding = "BOOKS_CACHE"
id = "b9cade63b6db48fd80c109a013f38fdb"

# Your existing R2 bucket binding (update if different)
[[r2_buckets]]
binding = "BOOKS_R2"
bucket_name = "books-cache"